### ISSUE TITLE
section `.text1' will not fit in region `iram1_0_seg

### ISSUE THREAD

**Issue by slipx06** [Dilbert66/esphome-dsckeybus#11]
I moved my esphome to a new system and now I am getting a compile error. I thought it was related to ESPHome but downgrading the version did not fix the error below. Maybe a platfromIO issue. Running on Debian10  Any ideas

```
Linking /data/alarm/.pioenvs/alarm/firmware.elf
/root/.platformio/packages/toolchain-xtensa@2.40802.200502/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: /data/alarm/.pioenvs/alarm/firmware.elf section `.text1' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
*** [/data/alarm/.pioenvs/alarm/firmware.elf] Error 1
```

![image](https://user-images.githubusercontent.com/7227275/99046789-f2e22e80-259b-11eb-9057-0fe1cc9c2ea7.png)

**Comment by Dilbert66** [comment]
Yes, I see that. Tks.  I had not upgraded yet. .  Looks like some of the updated libraries used by esphome are using a lot more ram 
 than they were before. I have to see how to trim ram use.

**Comment by Dilbert66** [comment]
You can downgrade but you then need to delete the temporary compilation directory first or it will try and use the previous compile

**Comment by Dilbert66** [comment]
I've pushed a new version to the "dev" branch that compiles fine on the esphome 1.15.3.   A few changes needed to reduce memory useage. The problem is that esphome and the various libraries included, use a lot of ram which does not leave much for other use.  A lot of functions use ISR's which require the functions to live in RAM to function correctly so some memory size tricks and optimizations are needed.

**Comment by slipx06** [comment]
Thank you. Confirmed working int the new version
